[package]
name = "repllet"
version = "0.0.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.0.18", features = ["derive", "color"] }
rustyline = "10.0.0"


[[example]]
name = "simple"
