[package]
name = "repllet"
version = "0.0.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.0.18", features = ["derive", "color"] }
clap_complete = { version = "4.0.3", features = ["unstable-dynamic"] }
nu-ansi-term = "0.46.0"
reedline = { version = "0.13.0", features = ["external_printer"] }


[[example]]
name = "simple"
